let stockProductos = [
    {id: 1, nombre: "Combo 1", tipo: "Combo", cantidad: 1, desc: "...", precio: 1200, tipo: "L", img: './img/frutos.jpg'},
    {id: 2, nombre: "Combo 2", tipo: "Combo", cantidad: 1, desc: "...", precio: 1100, tipo: "L", img: './img/frutos.jpg'},
    {id: 3, nombre: "Combo 3", tipo: "Combo", cantidad: 1, desc: "...", precio: 1200, tipo: "M", img: './img/frutos.jpg'},
    {id: 4, nombre: "Combo 4", tipo: "Combo", cantidad: 1, desc: "...", precio: 1400, tipo: "M", img: './img/frutos.jpg'},
    {id: 5, nombre: "Combo 5", tipo: "Combo", cantidad: 1, desc: "...", precio: 1200, tipo: "S", img: './img/frutos.jpg'},
    {id: 6, nombre: "Combo 6", tipo: "Combo", cantidad: 1, desc: "...", precio: 1500, tipo: "S", img: './img/frutos.jpg'},
    {id: 7, nombre: "Pack 1", tipo: "Pack", cantidad: 1, desc: "...", precio: 500, tipo: "L", img: './img/frutos.jpg'},
    {id: 8, nombre: "Pack 2", tipo: "Pack", cantidad: 1, desc: "...", precio: 500, tipo: "L", img: './img/frutos.jpg'},
    {id: 9, nombre: "Pack 3", tipo: "Pack", cantidad: 1, desc: "...", precio: 500, tipo: "M", img: './img/frutos.jpg'},
    {id: 10, nombre: "Pack 4", tipo: "Pack", cantidad: 1, desc: "...", precio: 700, tipo: "M", img: './img/frutos.jpg'},
    {id: 11, nombre: "Pack 5", tipo: "Pack", cantidad: 1,desc: "...", precio: 700, tipo: "S", img: './img/frutos.jpg'},
    {id: 12, nombre: "Pack 6", tipo: "Pack", cantidad: 1, desc: "...", precio: 700, tipo: "S", img: './img/frutos.jpg'},
    {id: 13, nombre: "Producto 1", tipo: "Producto", cantidad: 1, desc: "...", precio: 900, tipo: "L", img: './img/frutos.jpg'},
    {id: 14, nombre: "Producto 2", tipo: "Producto", cantidad: 1, desc: "...", precio: 1400, tipo: "S", img: './img/frutos.jpg'},
    {id: 15, nombre: "Producto 3", tipo: "Producto", cantidad: 1, desc: "...", precio: 7000, tipo: "L", img: './img/frutos.jpg'},
    {id: 16, nombre: "Producto 4", tipo: "Producto", cantidad: 1, desc: "...", precio: 777, tipo: "S", img: './img/frutos.jpg'},
    {id: 17, nombre: "Producto 5", tipo: "Producto", cantidad: 1, desc: "...", precio: 234, tipo: "S", img: './img/frutos.jpg'},
    {id: 18, nombre: "Producto 6", tipo: "Producto", cantidad: 1, desc: "...", precio: 155600, tipo: "M", img: './img/frutos.jpg'},
    {id: 19, nombre: "Mix 1", tipo: "Mix", cantidad: 1, desc: "...", precio: 1600, tipo: "L", img: './img/frutos.jpg'},
    {id: 20, nombre: "Mix 2", tipo: "Mix", cantidad: 1, desc: "...", precio: 3200, tipo: "L", img: './img/frutos.jpg'},
    {id: 21, nombre: "Mix 3", tipo: "Mix", cantidad: 1, desc: "...", precio: 2300, tipo: "M", img: './img/frutos.jpg'},
    {id: 22, nombre: "Mix 4", tipo: "Mix", cantidad: 1, desc: "...", precio: 5600, tipo: "M", img: './img/frutos.jpg'},
    {id: 23, nombre: "Mix 5", tipo: "Mix", cantidad: 1, desc: "...", precio: 1700, tipo: "S", img: './img/frutos.jpg'},
    {id: 24, nombre: "Mix 6", tipo: "Mix", cantidad: 1, desc: "...", precio: 800, tipo: "S", img: './img/frutos.jpg'},
]